import { StyleSheet } from "react-native";
import { mainHPadding } from "../../../constant";
import { fontSize } from "../../../utils/responsiveSize";
import { FONTS } from "../../../assets/fonts";
import { COLORS } from "../../../macros/colors";

const styles = StyleSheet.create({
  mainChartView: {
    gap: 25,
  },
  container: { flex: 1 },
  innerContainer: {
    flex: 1,
    paddingHorizontal: mainHPadding,
    gap: 12,
    paddingBottom: 24,
  },
  headerView: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    paddingHorizontal: mainHPadding,
    paddingTop: 8,
    paddingBottom: 14,
    zIndex: 9999999,
  },
  headerTitleWrap: { flex: 1 },
  headerEyebrow: {
    fontSize: fontSize(3.2),
    fontFamily: FONTS.Bold_700,
    letterSpacing: 0.2,
  },
  headerTitle: {
    fontSize: fontSize(8),
    fontFamily: FONTS.ExtraBold_800,
    letterSpacing: -0.8,
  },
  dashboard: { gap: 12 },
  heroCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 18,
    padding: 18,
    borderRadius: 30,
    borderCurve: "continuous",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.35,
    shadowRadius: 24,
    elevation: 6,
  },
  heroBody: { flex: 1, gap: 2 },
  heroEyebrow: { fontSize: fontSize(3.3), fontFamily: FONTS.Bold_700 },
  heroNumber: {
    fontSize: fontSize(9),
    fontFamily: FONTS.ExtraBold_800,
    letterSpacing: -1,
  },
  heroUnit: { fontSize: fontSize(4), fontFamily: FONTS.Bold_700 },
  heroTargetPill: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 6,
    marginTop: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 100,
  },
  heroTargetText: { fontSize: fontSize(3.2), fontFamily: FONTS.Bold_700 },
  heroLoader: { position: "absolute", top: 14, right: 16 },
  ringCenter: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
  },
  ringValue: {
    fontSize: fontSize(6.6),
    fontFamily: FONTS.ExtraBold_800,
    letterSpacing: -0.6,
  },
  ringCaption: { fontSize: fontSize(2.8), fontFamily: FONTS.SemiBold_600 },
  metricRow: { gap: 12 },
  weightCard: {
    gap: 14,
    padding: 14,
    borderRadius: 24,
    borderCurve: "continuous",
    borderWidth: StyleSheet.hairlineWidth,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 2,
  },
  weightHead: { flexDirection: "row", alignItems: "center", gap: 10 },
  weightStatusRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  weightStatusDot: { height: 7, width: 7, borderRadius: 100 },
  weightInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingLeft: 16,
    paddingRight: 6,
    height: 60,
    borderRadius: 20,
    borderCurve: "continuous",
    borderWidth: 1.5,
  },
  weightInput: {
    minWidth: 60,
    fontSize: fontSize(7.4),
    fontFamily: FONTS.ExtraBold_800,
    letterSpacing: -0.8,
    paddingVertical: 0,
  },
  weightUnit: { fontSize: fontSize(4), fontFamily: FONTS.Bold_700 },
  actionSpacerFlex: { flex: 1 },
  weightSave: {
    height: 46,
    paddingHorizontal: 22,
    borderRadius: 100,
    alignItems: "center",
    justifyContent: "center",
  },
  weightSaveText: { fontSize: fontSize(3.7), fontFamily: FONTS.Bold_700 },
  weightError: {
    fontSize: fontSize(3),
    fontFamily: FONTS.Medium_500,
    marginTop: -6,
    marginLeft: 6,
  },
  metricTile: {
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 24,
    borderCurve: "continuous",
    borderWidth: StyleSheet.hairlineWidth,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 2,
  },
  metricHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  metricValueRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
  },
  metricLabel: { fontSize: fontSize(3.3), fontFamily: FONTS.Bold_700 },
  metricValue: {
    fontSize: fontSize(6),
    fontFamily: FONTS.ExtraBold_800,
    letterSpacing: -0.5,
  },
  metricUnit: { fontSize: fontSize(3.1), fontFamily: FONTS.SemiBold_600 },
  metricTrack: {
    height: 8,
    borderRadius: 100,
    overflow: "hidden",
    marginTop: 2,
  },
  metricFill: { height: "100%", borderRadius: 100 },
  metricFoot: { fontSize: fontSize(2.9), fontFamily: FONTS.SemiBold_600 },
  topInputMargin: {
    marginTop: 14,
  },
  logo: {
    height: 50,
    width: 132,
    resizeMode: "contain",
  },
  rightIconsView: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  filterView: {
    borderWidth: 0.5,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 100,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  menuIcon: {
    height: 28,
    width: 28,
    resizeMode: "contain",
  },
  headingText: {
    fontSize: fontSize(4),
    fontFamily: FONTS.Medium_500,
    color: COLORS.HEADING,
    marginBottom: 8,
  },
  filterText: {
    fontSize: fontSize(3.2),
    fontFamily: FONTS.Medium_500,
    textTransform: "capitalize",
  },
  scrollText: {
    fontSize: fontSize(2.6),
    fontStyle: "italic",
    color: COLORS.TEXT,
    marginTop: 5,
    textAlign: "center",
  },
  noFoundView: {
    paddingBottom: 12,
    minHeight: 120,
    alignItems: "center",
    justifyContent: "center",
  },
  noFoundText: {
    fontSize: fontSize(3.9),
    color: COLORS.TEXT,
    textAlign: "center",
  },
  view: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 24,
    borderCurve: "continuous",
    padding: 16,
    flexShrink: 1,
    overflow: "hidden",
  },
  viewScroll: {
    gap: 12,
    flexShrink: 1,
  },
  iconView: {
    height: 35,
    width: 35,
    backgroundColor: COLORS.BACKGROUND,
    borderRadius: 100,
    alignItems: "center",
    justifyContent: "center",
  },
  itemView: {
    flexDirection: "row",
    gap: 12,
    flexShrink: 1,
  },
  icon: {
    height: 35,
    width: 35,
    resizeMode: "contain",
  },
  iconImg: {
    height: 17,
    width: 17,
    resizeMode: "contain",
    marginTop: 2.5,
  },
  textRightView: {
    flexShrink: 1,
  },
  desText: {
    fontSize: fontSize(3.6),
    fontFamily: FONTS.Regular_400,
    color: COLORS.HEADING,
    flexShrink: 1,
  },
  optionView: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  optionTile: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
    borderRadius: 22,
    borderCurve: "continuous",
    borderWidth: StyleSheet.hairlineWidth,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 2,
  },
  optionTilePressed: { opacity: 0.8, transform: [{ scale: 0.97 }] },
  optionIconWrap: {
    height: 40,
    width: 40,
    borderRadius: 13,
    borderCurve: "continuous",
    alignItems: "center",
    justifyContent: "center",
  },
  optionIcon: { height: 18, width: 18, resizeMode: "contain" },
  optionTextWrap: { flex: 1 },
  optionCaption: { fontSize: fontSize(3), fontFamily: FONTS.Medium_500 },
  arrow: {
    height: 16,
    width: 16,
    resizeMode: "contain",
  },
  labelTextOption: {
    fontSize: fontSize(3.7),
    fontFamily: FONTS.Bold_700,
    color: COLORS.HEADING,
  },
  referralView: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 15,
    backgroundColor: COLORS.WHITE,
    borderRadius: 100,
    padding: 15,
    borderWidth: 0.5,
    borderColor: COLORS.PRIMARY,
  },
  referralViewIcon: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  // ===========
  fabButton: {
    position: "absolute",
    bottom: 50,
    right: 50,
  },
  inCard: {
    gap: 10,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  progressView: {
    backgroundColor: COLORS.BACKGROUND,
    height: 8,
    borderRadius: 100,
    position: "relative",
    width: "100%",
    overflow: "hidden",
  },
  progress: {
    height: "100%",
    borderRadius: 100,
  },
  bgColor: {
    backgroundColor: COLORS.RED,
  },
  countView: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flex: 0.7,
  },
  label: {
    width: "40%",
    fontSize: fontSize(3.6),
    fontFamily: FONTS.Medium_500,
    color: COLORS.HEADING,
    flexShrink: 1,
  },
  view1: {
    width: "30%",
  },
  heading: {
    fontSize: fontSize(3.3),
    fontFamily: FONTS.Medium_500,
    color: COLORS.HEADING,
    flexShrink: 1,
  },
  count: {
    fontSize: fontSize(4),
    fontFamily: FONTS.SemiBold_600,
    color: COLORS.HEADING,
    flexShrink: 1,
  },
  normal: {
    fontSize: fontSize(3.6),
    fontFamily: FONTS.Regular_400,
    // color: COLORS.TEXT,
  },
  editRowTarget: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  editIcon: {
    height: 14,
    width: 14,
    resizeMode: "contain",
    marginBottom: 2,
  },
  sheetContent: {
    width: "100%",
    paddingHorizontal: mainHPadding,
    paddingTop: 10,
    gap: 16,
  },
  sheetTitle: {
    fontSize: fontSize(4),
    fontFamily: FONTS.SemiBold_600,
    color: COLORS.HEADING,
  },
});

export default styles;
