import { Dimensions, StyleSheet } from "react-native";
import { COLORS } from "../../macros/colors";
import { fontSize, height } from "../../utils/responsiveSize";
import { FONTS } from "../../assets/fonts";
import { mainHPadding } from "../../constant";

const { width: SW } = Dimensions.get("window");

export const FRAME_SIZE = SW * 0.78;
export const CORNER_SZ = 28;
export const C_THICK = 3;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: "relative",
  },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: mainHPadding * 2,
    gap: 15,
  },
  btnView: {
    width: "50%",
  },
  looksLikeText: {
    color: COLORS.TEXT,
    fontSize: fontSize(3.5),
    fontFamily: FONTS.Regular_400,
    letterSpacing: 0.5,
    textAlign: "center",
  },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  bottomButtons: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingBottom: 10,
  },
  button: {
    height: 52,
    width: 52,
    borderRadius: 100,
    borderWidth: StyleSheet.hairlineWidth,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 3,
  },
  button2: {
    height: 52,
    width: 52,
  },
  imgIcon: {
    height: 22,
    width: 22,
    resizeMode: "contain",
  },
  scanControls: {
    width: "100%",
    alignItems: "center",
    gap: 14,
    paddingBottom: 10,
  },
  scanHint: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 100,
  },
  scanHintText: { fontSize: fontSize(3.2), fontFamily: FONTS.SemiBold_600 },
  scanShutterInner: { alignItems: "center", justifyContent: "center" },
  actionIcon: {
    height: 27,
    width: 27,
    resizeMode: "contain",
  },
  btnText: {
    color: COLORS.WHITE,
    fontSize: fontSize(3.5),
    fontFamily: FONTS.Regular_400,
    letterSpacing: 0.5,
  },
  nextText: {
    color: COLORS.WHITE,
    fontSize: fontSize(4.2),
    fontFamily: FONTS.Medium_500,
  },
  borderCircle: {
    width: 82,
    height: 82,
    borderWidth: 4,
    borderColor: COLORS.WHITE,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  innerCircle: {
    width: 66,
    height: 66,
    borderRadius: 100,
  },
  previewContainer: {
    flex: 1,
    backgroundColor: COLORS.BLACK,
    justifyContent: "center",
    alignItems: "center",
  },
  previewImage: {
    width: "100%",
    height: "100%",
  },
  previewButtons: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: COLORS.MIRROR_BG,
    height: 70,
  },
  zoomView: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: height(3),
    alignSelf: "center",
    backgroundColor: COLORS.MIRROR_BG,
    padding: 4,
    borderRadius: 100,
    gap: 2,
    zIndex: 99,
  },
  zoomButton: {
    height: 35,
    width: 35,
    borderRadius: 100,
    backgroundColor: COLORS.TRANSPARENT,
    justifyContent: "center",
    alignItems: "center",
  },
  zoomButtonActive: {
    backgroundColor: COLORS.WHITE,
  },
  zoomText: {
    fontSize: fontSize(3.5),
    lineHeight: fontSize(4.5),
    color: COLORS.WHITE,
    fontFamily: FONTS.Medium_500,
  },
  zoomTextActive: {
    color: COLORS.TEXT,
  },
  topRowView: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: mainHPadding,
    zIndex: 9999999,
  },
  flashView: {
    width: 40,
    height: 40,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    padding: 5,
  },
  activeFlash: {
    backgroundColor: `${COLORS.GOLD}22`,
    borderColor: `${COLORS.GOLD}80`,
  },
  frameWrapView: {
    position: "absolute",
    width: 55,
    height: 55,
    backgroundColor: "rgba(0,0,0,.7)",
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 2,
    paddingLeft: 1,
  },
  frameWrap: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 999999,
  },
  warmUpOverlay: {
    alignItems: "center",
    justifyContent: "center",
  },
  viewShot: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    // zIndex:1
  },
  liveCaptureView: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 99999,
  },
  topHeaderView: {
    zIndex: 9999999,
    alignItems: "flex-end",
    paddingHorizontal: mainHPadding,
  },
  shareCircleView: {
    height: 45,
    width: 45,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  frame: {
    width: FRAME_SIZE,
    height: FRAME_SIZE,
    alignItems: "center",
    justifyContent: "center",
  },
  innerBorder: {
    position: "absolute",
    width: FRAME_SIZE - 2,
    height: FRAME_SIZE - 2,
    borderWidth: 1,
    borderColor: "rgba(0,255,194,0.09)",
  },
  corner: { position: "absolute", zIndex: 10 },
  cTL: { top: -2, left: -2 },
  cTR: { top: -2, right: -2 },
  cBL: { bottom: -2, left: -2 },
  cBR: { bottom: -2, right: -2 },

  // ========== Result Sheet

  sheetScrim: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(4,8,20,0.20)",
  },
  resultSheet: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingBottom: 30,
    shadowColor: COLORS.MIRROR_BG,
    shadowOpacity: 0.5,
    shadowRadius: 40,
    shadowOffset: { width: 0, height: -6 },
    elevation: 28,
    zIndex: 9999999999,
    paddingHorizontal: mainHPadding,
  },
  sheetHandle: {
    width: 38,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(0,0,0,0.7)",
    alignSelf: "center",
    marginTop: 14,
    marginBottom: 2,
  },
  sheetHead: {
    flexShrink: 1,
    paddingTop: 12,
    paddingBottom: 10,
    gap: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sheetTitle: {
    fontSize: fontSize(4.7),
    fontFamily: FONTS.SemiBold_600,
    flexShrink: 1,
  },
  sheetSub: {
    color: COLORS.TEXT,
    fontSize: fontSize(3.7),
    marginBottom: 15,
    fontFamily: FONTS.Medium_500,
  },
  bold: {
    color: COLORS.HEADING,
    fontFamily: FONTS.SemiBold_600,
  },

  macroSection: { marginTop: 8, gap: 8 },
  macroRow: { flexDirection: "row", gap: 10 },
  macroCard: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    borderWidth: 0.45,
    borderColor: COLORS.BORDER_COLOR,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 3,
  },
  macroIcon: { fontSize: fontSize(5), marginBottom: 2 },
  macroVal: {
    fontSize: fontSize(4.5),
    fontFamily: FONTS.Bold_700,
    color: COLORS.HEADING,
  },
  macroUnit: {
    fontSize: fontSize(3.5),
    fontFamily: FONTS.Bold_700,
    color: COLORS.HEADING,
  },
  macroLabel: {
    color: COLORS.HEADING,
    fontSize: fontSize(3.2),
    fontFamily: FONTS.Regular_400,
  },
  macroTrack: {
    width: "100%",
    height: 3,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.07)",
    overflow: "hidden",
    marginTop: 10,
  },
  macroFill: { height: "100%", borderRadius: 2 },

  scanAgainBtn: {
    marginHorizontal: 18,
    backgroundColor: COLORS.PRIMARY,
    borderRadius: 16,
    paddingVertical: 17,
    alignItems: "center",
    shadowColor: COLORS.PRIMARY,
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 4 },
    elevation: 14,
  },
  scanAgainText: {
    color: COLORS.BACKGROUND,
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
});

export default styles;
